import assert from 'node:assert/strict';
import { platform } from 'node:os';
import { describe, test } from 'node:test';

import {
  dnsSearchArgs,
  hostSearchDomains,
  isSafeSearchDomain,
  parseOverride,
  parseResolvConfSearchDomains,
  parseScutilSearchDomains,
  parseWindowsSearchDomains,
  resetSearchDomainCache,
} from './docker-dns';
import { type ProcessRunner } from './process';

/** A fragment of real `scutil --dns` output: the same domains, once per resolver. */
const SCUTIL = `
DNS configuration

resolver #1
  search domain[0] : corp.example.net
  search domain[1] : example.net
  nameserver[0] : 10.0.0.1
  flags    : Request A records, Request AAAA records

resolver #2
  domain   : local
  search domain[0] : corp.example.net
  options  : mdns
`;

describe('parseScutilSearchDomains', () => {
  test('reads the search list in order, without the resolver repeats', () => {
    assert.deepEqual(parseScutilSearchDomains(SCUTIL), ['corp.example.net', 'example.net']);
  });

  test('is empty for output that declares no search domains', () => {
    assert.deepEqual(parseScutilSearchDomains('resolver #1\n  nameserver[0] : 8.8.8.8\n'), []);
  });
});

describe('parseResolvConfSearchDomains', () => {
  test('reads both the search list and a lone domain directive', () => {
    const resolv = [
      '# Generated by NetworkManager',
      'nameserver 10.0.0.1',
      'search corp.example example.net',
      'domain corp.example',
      'options ndots:2',
    ].join('\n');
    assert.deepEqual(parseResolvConfSearchDomains(resolv), ['corp.example', 'example.net']);
  });

  test('ignores commented-out directives', () => {
    assert.deepEqual(parseResolvConfSearchDomains('# search commented.example\n'), []);
  });
});

describe('parseWindowsSearchDomains', () => {
  /**
   * What the two cmdlets print together: the machine-wide suffix search list,
   * then one line per adapter — including the empty ones for adapters that have
   * no connection-specific suffix, and a repeat of a domain already listed.
   */
  const POWERSHELL = ['corp.example.net', 'example.net', '', 'corp.example.net', ''].join('\r\n');

  test('reads both cmdlets, de-duplicated and in order', () => {
    assert.deepEqual(parseWindowsSearchDomains(POWERSHELL), ['corp.example.net', 'example.net']);
  });

  test('is empty when neither cmdlet has anything to say', () => {
    assert.deepEqual(parseWindowsSearchDomains('\r\n\r\n'), []);
    assert.deepEqual(parseWindowsSearchDomains(''), []);
  });
});

describe('normalisation', () => {
  test('drops anything that is not a hostname', () => {
    assert.deepEqual(parseOverride('ok.example, bad_domain, -bad.example, a..b'), ['ok.example']);
  });

  test('a space separates domains as readily as a comma', () => {
    assert.deepEqual(parseOverride('a.example b.example'), ['a.example', 'b.example']);
  });

  test('lower-cases and strips the root dot, so duplicates collapse', () => {
    assert.deepEqual(parseOverride('Corp.Example., corp.example'), ['corp.example']);
  });

  test('keeps at most the six domains resolv.conf honours', () => {
    const domains = ['a', 'b', 'c', 'd', 'e', 'f', 'g'].map((label) => `${label}.example`);
    assert.deepEqual(parseOverride(domains.join(',')), domains.slice(0, 6));
  });

  test('stops before the 256-character resolv.conf limit', () => {
    // 108 characters each: two fit in the `search` line, the third does not.
    const long = `${'x'.repeat(100)}.example`;
    assert.deepEqual(
      parseOverride([long, long.replace('x', 'y'), long.replace('x', 'z')].join(',')),
      [long, long.replace('x', 'y')],
    );
  });
});

describe('isSafeSearchDomain', () => {
  test('accepts a hostname and refuses what could not be one', () => {
    assert.equal(isSafeSearchDomain('corp.example.net'), true);
    assert.equal(isSafeSearchDomain('a-b.example'), true);
    assert.equal(isSafeSearchDomain('--dns-search'), false);
    assert.equal(isSafeSearchDomain('host name'), false);
    assert.equal(isSafeSearchDomain(''), false);
  });
});

describe('hostSearchDomains', () => {
  /** Fails on any call: the override path must not shell out at all. */
  const forbiddenRunner: ProcessRunner = {
    run: () => Promise.reject(new Error('should not run a process')),
  };

  const withOverride = async (
    value: string | undefined,
    body: () => Promise<void>,
  ): Promise<void> => {
    const previous = process.env.AGENT_ENGINE_DNS_SEARCH;
    if (value === undefined) {
      delete process.env.AGENT_ENGINE_DNS_SEARCH;
    } else {
      process.env.AGENT_ENGINE_DNS_SEARCH = value;
    }
    resetSearchDomainCache();
    try {
      await body();
    } finally {
      if (previous === undefined) {
        delete process.env.AGENT_ENGINE_DNS_SEARCH;
      } else {
        process.env.AGENT_ENGINE_DNS_SEARCH = previous;
      }
      resetSearchDomainCache();
    }
  };

  test('the env override wins over detection', async () => {
    await withOverride('corp.example nexus.example', async () => {
      assert.deepEqual(await hostSearchDomains(forbiddenRunner), ['corp.example', 'nexus.example']);
    });
  });

  test('an empty override switches search domains off entirely', async () => {
    await withOverride('', async () => {
      assert.deepEqual(await hostSearchDomains(forbiddenRunner), []);
    });
  });

  // Only on macOS is the failing runner the whole of detection; elsewhere the
  // detector reads `/etc/resolv.conf`, whose contents are the machine's business.
  test(
    'a failed detection degrades to no search domains',
    { skip: platform() === 'darwin' ? false : 'reads /etc/resolv.conf off macOS' },
    async () => {
      await withOverride(undefined, async () => {
        assert.deepEqual(await hostSearchDomains(forbiddenRunner), []);
      });
    },
  );

  // The point of taking the platform as an argument: this is the branch nobody
  // on this team runs, so it has to be reachable from a test on macOS.
  test('on Windows it asks PowerShell, not /etc/resolv.conf', async () => {
    await withOverride(undefined, async () => {
      const calls: { command: string; args: string[] }[] = [];
      const runner: ProcessRunner = {
        run: (command, args) => {
          calls.push({ command, args });
          return Promise.resolve({ stdout: 'corp.example\r\nnexus.example\r\n', stderr: '' });
        },
      };

      assert.deepEqual(await hostSearchDomains(runner, 'win32'), ['corp.example', 'nexus.example']);
      assert.equal(calls.length, 1);
      assert.equal(calls[0].command, 'powershell');
      // `-NonInteractive` matters: a prompt here would hang container creation.
      assert.ok(calls[0].args.includes('-NonInteractive'));
      assert.ok(calls[0].args.some((arg) => arg.includes('Get-DnsClientGlobalSetting')));
    });
  });

  test('a Windows box without the DnsClient cmdlets still starts containers', async () => {
    await withOverride(undefined, async () => {
      const runner: ProcessRunner = {
        run: () => Promise.reject(new Error("'powershell' is not recognized")),
      };
      assert.deepEqual(await hostSearchDomains(runner, 'win32'), []);
    });
  });

  test('detection runs once per daemon', async () => {
    await withOverride(undefined, async () => {
      let calls = 0;
      const runner: ProcessRunner = {
        run: () => {
          calls += 1;
          return Promise.resolve({ stdout: SCUTIL, stderr: '' });
        },
      };
      const first = await hostSearchDomains(runner);
      const second = await hostSearchDomains(runner);
      assert.deepEqual(first, second);
      assert.ok(calls <= 1, 'the host resolver configuration is read at most once');
    });
  });
});

describe('dnsSearchArgs', () => {
  test('repeats the flag per domain, and is empty for none', () => {
    assert.deepEqual(dnsSearchArgs(['a.example', 'b.example']), [
      '--dns-search',
      'a.example',
      '--dns-search',
      'b.example',
    ]);
    assert.deepEqual(dnsSearchArgs([]), []);
  });
});
